# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# Creating an array from a python list
a=np.array([1,2,3,4,5.7,12])
a

array([ 1. ,  2. ,  3. ,  4. ,  5.7, 12. ])

In [7]:
# Accessing an element in a array
a[2]

np.float64(3.0)

In [8]:
# Replacing an element in an array
a[2]=10

In [9]:
a

array([ 1. ,  2. , 10. ,  4. ,  5.7, 12. ])

In [10]:
# Creating a range from one to 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
# Creating an array filled with numbers from a certain parameter to another
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays


In [13]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#Accessing elements in a multi-dimensional array
n= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

p=n[0,1]
p

np.int64(2)

In [16]:
# Accessing a row in an array
n[2]

array([7, 8, 9])

In [17]:
# Replacing the entire row in an array

n[2]= [8,7,3]

n

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 3]])

In [18]:
# Accessing an entire column in an array

n[:, 2]

array([3, 6, 3])

# Randomly generated arrays

In [19]:
np.random.rand(5, 2)

array([[0.77456918, 0.09412878],
       [0.51313784, 0.20968766],
       [0.87509088, 0.28894061],
       [0.17163482, 0.33897197],
       [0.84176786, 0.09324663]])

In [20]:
# Making the random function get the same results each time we execute the cell/notebook
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [21]:
# Generating numbers with a standard normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [22]:
# Generating random integers
np.random.seed(2)
np.random.randint(low=0, high=100, size =(5, 2) )

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [23]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
# Multiplication
b= a * 2
b

array([0, 2, 4, 6, 8])

In [25]:
# Adding different arrays 
a + b


array([ 0,  3,  6,  9, 12])

# Comparison Operations

In [26]:
a

array([0, 1, 2, 3, 4])

In [27]:
a >= 2

array([False, False,  True,  True,  True])

In [28]:
a > b

array([False, False, False, False, False])

In [30]:
a[ a > b ]

array([], dtype=int64)

# Summarizing Operations

In [31]:
a

array([0, 1, 2, 3, 4])

In [32]:
a.sum()

np.int64(10)

In [33]:
a.std()

np.float64(1.4142135623730951)

In [34]:
a.min()

np.int64(0)