# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
# Creating an array from a python list
a=np.array([1,2,3,4,5.7,12])
a

array([ 1. ,  2. ,  3. ,  4. ,  5.7, 12. ])

In [8]:
# Accessing an element in a array
a[2]

np.float64(3.0)

In [9]:
# Replacing an element in an array
a[2]=10

In [10]:
a

array([ 1. ,  2. , 10. ,  4. ,  5.7, 12. ])

In [11]:
# Creating a range from one to 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
# Creating an array filled with numbers from a certain parameter to another
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays


In [15]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])