# Introduction to Numpy

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
# Creating an array from a python list
a=np.array([1,2,3,4,5.7,12])
a

array([ 1. ,  2. ,  3. ,  4. ,  5.7, 12. ])

In [8]:
# Accessing an element in a array
a[2]

np.float64(3.0)

In [9]:
# Replacing an element in an array
a[2]=10

In [10]:
a

array([ 1. ,  2. , 10. ,  4. ,  5.7, 12. ])

In [11]:
# Creating a range from one to 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
# Creating an array filled with numbers from a certain parameter to another
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays


In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#Accessing elements in a multi-dimensional array
n= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

p=n[0,1]
p

np.int64(2)

In [17]:
# Accessing a row in an array
n[2]

array([7, 8, 9])

In [18]:
# Replacing the entire row in an array

n[2]= [8,7,3]

n

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 3]])

In [19]:
# Accessing an entire column in an array

n[:, 2]

array([3, 6, 3])

# Randomly generated arrays

In [20]:
np.random.rand(5, 2)

array([[0.56971537, 0.00604522],
       [0.94221625, 0.07096989],
       [0.0264704 , 0.97184573],
       [0.8742375 , 0.07050352],
       [0.28454138, 0.2995731 ]])

In [21]:
# Making the random function get the same results each time we execute the cell/notebook
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
# Generating numbers with a standard normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
# Generating random integers
np.random.seed(2)
np.random.randint(low=0, high=100, size =(5, 2) )

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [24]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
# Multiplication
b= a * 2
b

array([0, 2, 4, 6, 8])

In [26]:
# Adding different arrays 
a + b


array([ 0,  3,  6,  9, 12])

# Comparison Operations

In [27]:
a

array([0, 1, 2, 3, 4])

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [29]:
a > b

array([False, False, False, False, False])

In [30]:
a[ a > b ]

array([], dtype=int64)

# Summarizing Operations

In [31]:
a

array([0, 1, 2, 3, 4])

In [32]:
a.sum()

np.int64(10)

In [33]:
a.std()

np.float64(1.4142135623730951)

In [34]:
a.min()

np.int64(0)

# Linear Algebra Refresher

## Matrix Operations

### 1. Vector- Vector Multiplication

In [35]:
# A function performing the Dot-Product between two vectors

def vector_vector_multiplication(u, v):
   assert u.shape[0]== v.shape[0] # Checking if the vectors are of the same dimensionality

   n = u.shape[0]

   result = 0.0

   for i in range(n):
       result= result + u[i] *  v[i]

   return result
  


In [36]:
u= np.array([2,4,5,6])
v= np.array([1,0,0,2])


In [37]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [38]:
# Alternatively, we could use:

u.dot(v)

np.int64(14)

### Matrix-Vector Multiplication

In [39]:
U = np.array([
     [2, 4, 5, 6],
     [1, 2, 1, 2],
     [3, 1, 2, 1],
])  

In [40]:
# A function that does the matrix-vector multiplication

def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np. zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

    

    

In [41]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [42]:
# Alternatively we could use:

U.dot(v)

array([14,  5,  5])

### Matrix-Matrix Multiplication

In [43]:
V= np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [44]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1]== V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result= np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi= V[:, i]
        Uvi=matrix_vector_multiplication(U, vi)
        result[:, i]= Uvi

    return result

In [45]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [46]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity Matrix

In [48]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [51]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Inverse

In [54]:
Vs= V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [56]:
# To perform the inverse of the above matrix we use:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [57]:
Vs. dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])